import type { Metadata } from "next";
import Navbar from "../_components/navbar";
import { cookies } from "next/headers";
import { decrypt } from "@/lib/session";
import { UserProvider, useUserContext } from "@/hooks/user";
import { ProtectedUser } from "@/lib/types";

export const metadata: Metadata = {
  title: "Dashboard | leetcode-leaderboard",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = cookies();
  const authToken = cookieStore.get("session");
  const user = (await decrypt(authToken?.value)) as ProtectedUser;
  return (
    <UserProvider user={user}>
      <main>
        <Navbar />
        {children}
      </main>
    </UserProvider>
  );
}
